In [1]:
#Realizar 3 tipos de classificadores, com o dataset de áudio
def parser(row):
   # function to load files and extract features
    if row.ID.endswith('.wav'):
        file_name = './validate/'+row.ID
    else:
        file_name = './train/Train/'+str(row.ID)+'.wav'
    try:
        print file_name
        X, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
        mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=100).T,axis=0)
    except Exception as e:
        print ("Error encountered: ", file_name, e)
        return None, None
    feature = mfccs
    if row.Class != 'gun_shot':
        label = '0'
    else:
        label = 1
    
    return [feature, label]


In [ ]:
import librosa
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

train_data = pd.read_csv('./train/train.csv')
temp = train_data.apply(parser, axis=1)
temp.columns = ['feature', 'label']

X = np.array(temp.feature.tolist())
y = np.array(temp.label.tolist())


print "Features loaded"

./train/Train/0.wav
./train/Train/0.wav
./train/Train/1.wav
./train/Train/2.wav
./train/Train/3.wav
./train/Train/4.wav
./train/Train/6.wav
./train/Train/10.wav
./train/Train/11.wav
./train/Train/12.wav
./train/Train/15.wav
./train/Train/17.wav
./train/Train/18.wav
./train/Train/19.wav
./train/Train/20.wav
./train/Train/22.wav
./train/Train/24.wav
./train/Train/26.wav
./train/Train/27.wav
./train/Train/32.wav
./train/Train/33.wav
./train/Train/35.wav
./train/Train/36.wav
./train/Train/37.wav
./train/Train/38.wav
./train/Train/40.wav
./train/Train/42.wav
./train/Train/43.wav
./train/Train/44.wav
./train/Train/45.wav
./train/Train/46.wav
./train/Train/47.wav
./train/Train/48.wav
./train/Train/49.wav
./train/Train/50.wav
./train/Train/52.wav
./train/Train/54.wav
./train/Train/56.wav
./train/Train/57.wav
./train/Train/59.wav
./train/Train/60.wav
./train/Train/61.wav
./train/Train/63.wav
./train/Train/65.wav
./train/Train/66.wav
./train/Train/67.wav
./train/Train/68.wav
./train/Train/71.wav

./train/Train/575.wav
./train/Train/576.wav
./train/Train/578.wav
./train/Train/579.wav
./train/Train/580.wav
./train/Train/583.wav
./train/Train/584.wav
./train/Train/585.wav
./train/Train/586.wav
./train/Train/587.wav
./train/Train/589.wav
./train/Train/590.wav
./train/Train/593.wav
./train/Train/594.wav
./train/Train/597.wav
./train/Train/598.wav
./train/Train/599.wav
./train/Train/600.wav
./train/Train/603.wav
./train/Train/604.wav
./train/Train/605.wav
./train/Train/606.wav
./train/Train/607.wav
./train/Train/610.wav
./train/Train/611.wav
./train/Train/612.wav
./train/Train/613.wav
./train/Train/614.wav
./train/Train/615.wav
./train/Train/619.wav
./train/Train/620.wav
./train/Train/621.wav
./train/Train/622.wav
./train/Train/623.wav
./train/Train/624.wav
./train/Train/629.wav
./train/Train/630.wav
./train/Train/631.wav
./train/Train/633.wav
./train/Train/635.wav
./train/Train/636.wav
./train/Train/639.wav
./train/Train/642.wav
./train/Train/643.wav
./train/Train/645.wav
./train/Tr

./train/Train/1160.wav
./train/Train/1162.wav
./train/Train/1168.wav
./train/Train/1174.wav
./train/Train/1175.wav
./train/Train/1176.wav
./train/Train/1180.wav
./train/Train/1181.wav
./train/Train/1182.wav
./train/Train/1183.wav
./train/Train/1186.wav
./train/Train/1187.wav
./train/Train/1188.wav
./train/Train/1189.wav
./train/Train/1191.wav
./train/Train/1195.wav
./train/Train/1200.wav
./train/Train/1203.wav
./train/Train/1205.wav
./train/Train/1206.wav
./train/Train/1209.wav
./train/Train/1210.wav
./train/Train/1214.wav
./train/Train/1217.wav
./train/Train/1218.wav
./train/Train/1219.wav
./train/Train/1220.wav
./train/Train/1224.wav
./train/Train/1226.wav
./train/Train/1228.wav
./train/Train/1230.wav
./train/Train/1231.wav
./train/Train/1232.wav
./train/Train/1235.wav
./train/Train/1236.wav
./train/Train/1237.wav
./train/Train/1240.wav
./train/Train/1241.wav
./train/Train/1242.wav
./train/Train/1243.wav
./train/Train/1244.wav
./train/Train/1245.wav
./train/Train/1246.wav
./train/Tra

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.25, random_state=50)


In [7]:
#Build Classifier Random Forest
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

parameters_regressor = {"max_depth": [2,3,4,5,6,7,8,9,10,11,12]
                        ,"min_samples_split" :[2,3,4,5,6]
                        ,"n_estimators" : [10]
                        ,"min_samples_leaf": [1,2,3,4,5]
                        ,"max_features": (2,3,4)}

X_RF_train = X_train
y_RF_train = y_train
y_RF_test = y_test
X_RF_test = X_test

parameters_classifier = {"max_depth": [2,3,4,5,6,7,8,9,10,11,12]
            ,"min_samples_split" :[2,3,4,5,6]
            ,"n_estimators" : [10]
            ,"min_samples_leaf": [1,2,3,4,5]
            ,"max_features": (4,5,6,"sqrt")
            ,"criterion": ('gini','entropy')}

rf_regr = RandomForestClassifier()

model_rcl = GridSearchCV(rf_regr,parameters_classifier, n_jobs = 3, cv = 10)


model_rcl.fit(X_train, y_train)

print model_rcl.best_params_

learned_parameters = model_rcl.best_params_

print('finished')


finished


In [8]:
rfc = RandomForestClassifier(max_depth = learned_parameters["max_depth"]
                            ,max_features = learned_parameters['max_features']
                            ,min_samples_leaf = learned_parameters['min_samples_leaf']
                            ,min_samples_split = learned_parameters['min_samples_split']
                            ,criterion = learned_parameters['criterion']
                            ,n_estimators = 5000
                            ,n_jobs = 3)
model_rcl = rfc.fit(X_train,y_train)
print model_rcl.score(X_test,y_test)
y_pred = model_rcl.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9694323144104804
             precision    recall  f1-score   support

          0       0.97      1.00      0.98      1295
          1       0.95      0.49      0.65        79

avg / total       0.97      0.97      0.96      1374

[[1293    2]
 [  40   39]]


In [9]:
#TEST 50%
0.9687045123726347
             precision    recall  f1-score   support

          0       0.97      1.00      0.98      2602
          1       0.97      0.42      0.59       146

avg / total       0.97      0.97      0.96      2748

[[2600    2]
 [  84   62]]

#TEST 75%
0.9655507035419699
             precision    recall  f1-score   support

          0       0.97      1.00      0.98      3911
          1       0.97      0.34      0.50       211

avg / total       0.97      0.97      0.96      4122

[[3909    2]
 [ 140   71]]

# TEST 25%
0.9694323144104804
             precision    recall  f1-score   support

          0       0.97      1.00      0.98      1295
          1       0.95      0.49      0.65        79

avg / total       0.97      0.97      0.96      1374

[[1293    2]
 [  40   39]]

IndentationError: unexpected indent (<ipython-input-9-91535ed5326b>, line 3)

In [10]:
#SVM CLASSIFIER
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC

X_SVM_train = X_train
X_SVM_test = X_test
y_SVM_train = y_train
y_SVM_test = y_test

param_grid = {'C': [1e3, 5e3, 1e4, 5e4, 1e5],
              'gamma': [0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1],
              'kernel': ['rbf', 'poly', 'sigmoid', 'precomputed']
              'decision_function_shape': ['ovo', 'ovr']}

clf_SVM = GridSearchCV(SVC(kernel='rbf', class_weight='balanced'), param_grid)
clf_SVM.fit(X_SVM_train,y_SVM_train)

print clf_SVM.best_params_

best_SVM_params = clf_SVM.best_params_

clf_SVM_best = SVC(kernel='rbf', class_weight='balanced', C= best_SVM_params['C'], gamma=best_SVM_params['gamma'])
clf_SVM_best.fit(X_train,y_train)

y_pred = clf_SVM_best.predict(X_test)

print(classification_report(y_test, y_pred))
print (clf_SVM_best.score(X_test, y_test))
print(confusion_matrix(y_test, y_pred))


             precision    recall  f1-score   support

          0       0.99      0.99      0.99      1295
          1       0.87      0.77      0.82        79

avg / total       0.98      0.98      0.98      1374

0.980349344978166
[[1286    9]
 [  18   61]]


In [11]:
# TESTE 50%
    precision    recall  f1-score   support

          0       0.99      0.99      0.99      2602
          1       0.86      0.82      0.84       146

avg / total       0.98      0.98      0.98      2748

0.9832605531295487
[[2583   19]
 [  27  119]]

# TESTE 75%
             precision    recall  f1-score   support

          0       0.98      1.00      0.99      3911
          1       0.93      0.64      0.76       211

avg / total       0.98      0.98      0.98      4122

0.9793789422610383
[[3901   10]
 [  75  136]]

# TESTE 25%
             precision    recall  f1-score   support

          0       0.99      0.99      0.99      1295
          1       0.87      0.77      0.82        79

avg / total       0.98      0.98      0.98      1374

0.980349344978166
[[1286    9]
 [  18   61]]

IndentationError: unexpected indent (<ipython-input-11-3e436b0b6189>, line 2)

In [ ]:
# #Neural Net Classifier
# from sklearn.model_selection import GridSearchCV
# from sklearn.metrics import classification_report
# from sklearn.metrics import confusion_matrix
# from sklearn.neural_network import MLPRegressor
# import numpy as np

# X_NN_train = X_train
# y_NN_train = y_train
# X_NN_test = X_test
# y_NN_train = y_test

# print y_train.shape
# print y_NN_train.shape


# param_grid = {'hidden_layer_sizes':[(5,),(10,), (100,), (1000,)]}
#              #'activation' : ['identity', 'logistic', 'tanh', 'relu'],
#              #'solver' : ['lbfgs', 'sgd', 'adam']}
# model_nn = MLPRegressor(random_state=50, max_iter=1000, verbose=True, hidden_layer_sizes=(5,))
# model_nn.fit(X_NN_train, y_train)

# best_NN_params = model_nn.best_params_
# print best_NN_params


In [ ]:
# model_nn_final = MLPRegressor(random_state=50, max_iter=1000, verbose=True, 
#                               hidden_layer_sizes=best_NN_params['hidden_layer_sizes'],
#                               alpha=best_NN_params['alpha'],
#                               solver=best_NN_params['solver'],
#                               activation=best_NN_params['activation'])

# model_nn_final.fit(X_NN_train, y_NN_train)

# y_pred = model_nn_final.predict(X_NN_test)


# print(classification_report(y_NN_test, y_pred))
# # print (clf.score(X_NN_test, y_NN_test))
# print(confusion_matrix(y_NN_test, y_pred))

In [12]:
## CNN
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.optimizers import Adam
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

X_CNN_train = X_train
y_CNN_train = y_train
X_CNN_test = X_test
y_CNN_test = y_test

lb = LabelEncoder()

transform = lb.fit_transform(y_CNN_train)

y_CNN_train = np_utils.to_categorical(transform)

print y_CNN_train

num_labels = y_CNN_train.shape[1]
filter_size = 2

#print num_labels
model = Sequential()

model.add(Dense(256, activation='relu', input_dim=100))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='elu'))
model.add(Dense(64, activation='elu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.summary()

#model.compile(optimizer='adam', loss='binary_crossentropy')
model.fit(X_train, y_train, epochs=20, validation_data=(X_test, y_test))

score2=model.evaluate(X_CNN_test, y_CNN_test, batch_size=128)

print score2

y_cnn_pred = model.predict_classes(X_CNN_test)
          

print(classification_report(y_test, y_cnn_pred))

print(confusion_matrix(y_test, y_cnn_pred))
          

/opt/conda/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [1. 0.]]
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 256)               25856     
_________________________________________________________________
dense_2 (Dense)              (None, 256)               65792     
_________________________________________________________________
dense_3 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_4 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_5 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 33        
Total params: 134,913
Trainable params: 134,913
Non-trainable params: 0
__________

In [14]:
file_name = './validate/gun-gunshot-01.wav'
#file_name = './test/Test/'+str(298)+'.wav'
try:
    X, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
    mfccs = np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=100).T,axis=0)
except Exception as e:
    print ("Error encountered: ", file_name, e)
feature = mfccs
label = 'siren'
#print X

X_Test2 = np.expand_dims(np.array(feature.tolist()),axis=0)

#print lb.get_params(y_CNN[2])

#print X_Test2
#print X_Test[0]
print 'CNN'
print model.predict_classes(X_Test2)

print lb.inverse_transform(model.predict_classes(X_Test2))

print 'SVM'
print clf_SVM_best.predict(X_Test2)

print 'RF'
print model_rcl.predict(X_Test2)

CNN
[[1]]
[['1']]
SVM
['1']
RF


/opt/conda/lib/python2.7/site-packages/sklearn/preprocessing/label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


['1']
